version: "3.8"
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: forum_db_08ka_user
      POSTGRES_PASSWORD: vlfOLLy9F6IwdgvxePIC5NqVOa34XKQ5
      POSTGRES_DB: forum_db_08ka
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forum_user"]
      interval: 5s
      retries: 10

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      # point to Postgres container (compose provides DNS 'db')
      DATABASE_URL: "postgresql://forum_db_08ka_user:vlfOLLy9F6IwdgvxePIC5NqVOa34XKQ5@dpg-d4ohu47gi27c738gn7j0-a/forum_db_08ka"
      SECRET_KEY: "change_me_for_prod"
      IMAGE_DIR: "/app/static/img"
      IMAGE_PRINCIPALE: "image_principale_ent.jpg"
      FLASK_ENV: "production"
      FLASK_APP: "app.py"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      # monte un dossier local images (pratique pour test / dev) :
      - ./static/images:/app/static/images
      # si tu veux persister sqlite (fallback) : 
      - ./data:/app
    restart: unless-stopped

volumes:
  pgdata:
